### NONFUNCTIONAL - DO NOT USE

FROM coreboot-base-env:latest

RUN ln /usr/bin /bin \
  && ln /bin/bash /bin/sh

RUN echo "root:x:0:0::/root:/sbin/nologin" > /etc/passwd \
 && echo "coreboot:x:1000:" > /etc/group \
 && mkdir -p /home/coreboot/coreboot/ \
 && adduser -h /home/coreboot -G coreboot -D -s /usr/bin/bash coreboot

ENTRYPOINT ["/usr/bin/bash"]

VOLUME ["/home/coreboot/coreboot/"]
